name: Deploy AWS Lambda

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read  # Required to check out the repository
    steps:
      - uses: actions/checkout@v7
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::781911158210:role/Github_Actions_Ridgeway_Warrior
          aws-region: us-west-2
      
      - name: Setup Node
        uses: "actions/setup-node@main"
        with: 
          node-version: 24
      
      - name: setup pnpm and install dependencies
        uses: pnpm/action-setup@v6.0.9
        with:
          version: 11.13
          cache: true
          cache_dependency_path: lambda-workflow-dispatcher/pnpm-lock.yaml
          run_install: |
            cwd: lambda-workflow-dispatcher

      - name: Build application with ESBuild
        run: |
          cd lambda-workflow-dispatcher
          pnpm build

      - name: Deploy Lambda Function
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: ridgway-warrior-workflow-caller 
          code-artifacts-dir: lambda-workflow-dispatcher/dist